{% set version = "1.24.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-logistf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/logistf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/logistf/logistf_{{ version }}.tar.gz
  sha256: e7e0d9054cf7f3221ba363afa0fdf1c8bb65b8841700ec0010fa4886be26a661

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mice
    - r-mgcv
    - r-formula.tools
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mice
    - r-mgcv
    - r-formula.tools

test:
  commands:
    - $R -e "library('logistf')"           # [not win]
    - "\"%R%\" -e \"library('logistf')\""  # [win]

about:
  home: http://cemsiis.meduniwien.ac.at/en/kb/science-research/software/statistical-software/fllogistf/
  license: GPL-2.0-or-later
  summary: Fit a logistic regression model using Firth's bias reduction method, equivalent to penalization of the log-likelihood by the Jeffreys  prior. Confidence intervals for regression coefficients can be computed by penalized profile likelihood. Firth's method was proposed as ideal solution to the problem of separation
    in logistic regression. If needed, the bias reduction can be turned off such that ordinary maximum likelihood logistic regression is obtained.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - slacalle

# Package: logistf
# Version: 1.23
# Date: 2018-07-19
# Title: Firth's Bias-Reduced Logistic Regression
# Authors@R: c(person("Georg", "Heinze", role=c("aut", "cre"), email="georg.heinze@meduniwien.ac.at"), person("Meinhard", "Ploner", role=c("aut")), person("Daniela","Dunkler", role=c("ctb")), person("Harry", "Southworth", role=c("ctb")))
# Depends: R (>= 3.0.0)
# Imports: mice, mgcv
# Description: Fit a logistic regression model using Firth's bias reduction method, equivalent to penalization of the log-likelihood by the Jeffreys  prior. Confidence intervals for regression coefficients can be computed by penalized profile likelihood. Firth's method was proposed as ideal solution to the problem of separation in logistic regression. If needed, the bias reduction can be turned off such that ordinary maximum likelihood logistic regression is obtained.
# License: GPL
# URL: http://cemsiis.meduniwien.ac.at/en/kb/science-research/software/statistical-software/fllogistf/
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2018-07-19 15:57:04 UTC; Biometrikus
# Author: Georg Heinze [aut, cre], Meinhard Ploner [aut], Daniela Dunkler [ctb], Harry Southworth [ctb]
# Maintainer: Georg Heinze <georg.heinze@meduniwien.ac.at>
# Repository: CRAN
# Date/Publication: 2018-07-19 17:40:10 UTC
