{% set version = "1.26.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-logistf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/logistf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/logistf/logistf_{{ version }}.tar.gz
  sha256: 351e0ffca232c0ffe29cbda53a3f5770dab30fb72b8223d782ee1ae5f37e8592

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-mice                       # [build_platform != target_platform]
    - r-mgcv                       # [build_platform != target_platform]
    - r-formula.tools              # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-mice
    - r-mgcv
    - r-formula.tools
  run:
    - r-base
    - r-matrix
    - r-mice
    - r-mgcv
    - r-formula.tools

test:
  commands:
    - $R -e "library('logistf')"           # [not win]
    - "\"%R%\" -e \"library('logistf')\""  # [win]

about:
  home: https://cemsiis.meduniwien.ac.at/en/kb/science-research/software/statistical-software/firth-correction/
  dev_url: https://github.com/georgheinze/logistf
  license: GPL-2.0-or-later
  summary: Fit a logistic regression model using Firth's bias reduction method, equivalent to penalization of the log-likelihood by the Jeffreys prior. Confidence intervals for regression coefficients can be computed by penalized profile likelihood. Firth's method was proposed as ideal solution to the problem of separation
    in logistic regression, see Heinze and Schemper (2002) <doi:10.1002/sim.1047>. If needed, the bias reduction can be turned off such that ordinary maximum likelihood logistic regression is obtained. Two new modifications of Firth's method, FLIC and FLAC, lead to unbiased predictions and are now available in the package
    as well, see Puhr et al (2017) <doi:10.1002/sim.7273>.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - slacalle
