travis:
  secure:
    BINSTAR_TOKEN: TBqYtyVDUFNxCI6vdWLVzQw7jS9tRP3a7QuvoI5vLm7lHLyDwPxEWU4uZ+nawyCL7DvF7acr8DgJ7KifEjyuJWJChX589wW3eccy3nATvl7GX9+JSFz6+wqcXYIBtRiBacSSutGHF5CaRQkeka75ZwFVXO2Ltgy3sUI/7oa2V4AHFpReEeEhhWJ5eOhZDKLIAufEVmk0vv6qIRkLbLMHXnoUh3db6eW0ZObKWBdXMgxRR7/nkhYLPllwU0/x7PXxUNgiXOg63qLAVozlEIClKRRuNWVBbooGf5QF4+4q5mRc3rfYiY46YQYyl8Yu9oQLR9c5WUudv9Vz0rPupR2lTrRWNUERHSVgtKUovx3Qq6KXEPMpBkyhaAp9rlu9pXHaJyLhB2yqlDPtQmOweVDxAMyKC9CxBbpDohXo5n/RD102lUk2dVs3NceIaaikv1BI+KrH/vu5q6QgzupeZi4Tuz8E2Htp8pnyZV4LUs4BzrGuzXfiu8iu5hlXU0aPzXh8Osq31V+mSeSNmwHW8agx+XTX4Y3O1UiVqQVPOwhl9116S3T2vdIpgHv7ocZe9FgrTf5IVN3zSq0YNDzwzapQ5e2kt4VNwIeXDwa4WyfZHy6AtRhfQpQSwbBJPAUZiVERO6PdCS8mGDPMZGsvWb3DeZNVAfojJIaNWDoSDujBO4o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
