appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JYq2cC4wyUgEe4YtAKbLyTfyMt9VtaZg8lnYyuWlQckmqonkcYwEmHOOa8HLsPRISn8xckz/zYoGsOy6kqbeUnR/03af/vkflguBiH2cZnrWpGWRfA5gyNU0jw9k2eb2RpBUJcCL69YmXCbYM4nbU9LB4ymI0c5GRcgRMCLCZBkcp/Rf4zohOAlaCkQd1DzCsKynV/+uSOEeuq/UpcRVZS212jJimeStpKqFwrSvMz5dSB/PuqBOjoURf+91P+J6O9u1FgUtWFoWKDwuig2OP9OY+/icTuaOKbcsOFFEUwJwoWH4bqbCSzXuJs5GFxO2HWj00VbrRY9zSMir1r/lxh2toMfGE3yYXDWXgEAW4XHltalNTIIRIlLVr+1pCSFz0r40y813Yna2NsJGyMKf2rOSArCmp3j2kXys1lWYDw7jKzxgy3EfQr8YxBsD5fJAzKczK5P0Rx9z3lmeRsQWNIFVHmDoK0G63hL9yHSSYu+Mgd6tsXrQRBH/jhQPiqcK1EqmKpQmCFIm+KWqSgdAQiJvZgMo91/wZRL3JQiwojvle8TtNYhOHkIO0xDGEUs0ha944nDU4RALgtIK6h+Uc6Z7X34jzDSRpr5L05eOT/Nrj+MrdQ2c2HDCHmW49JBwobZjfD9tREMwt67HItHFMkPnX/Z8s03GGU447Aza5rI=
